import { CatalogCourseInterface } from "@/types/course.types";

const mockData: CatalogCourseInterface[] = [
    {
        courseAddress: "EQBbFKeOGNLAX4vjeS7XvgpKFh0_3dVpampCsnXZUYyNOPKe",
        authorAddress: "0QA8-SVqn4H2dew-CzMrfzpqg2ReIQSYCFxkzpr4ZnwcunaS",
        title: "Изучаем Arduino",
        author: "Кантемир Курашинов",
        price: 15,
        duration: 50,
        rating: 4.8,
        image: "https://cdn.stepik.net/media/cache/images/courses/180519/cover_RqAtOM0/b9e65990d65b2f35546147d13003364c.jpg",
        users: 120,
        difficulty: "Intermediate",
        categories: ["programming"],
        date: "2024-11-15",
    },
    {
        courseAddress: "EQBbFKeOGNLAX4vjeS7XvgpKFh0_3dVpampCsnXZUYyNOPKe",
        authorAddress: "0QA8-SVqn4H2dew-CzMrfzpqg2ReIQSYCFxkzpr4ZnwcunaS",
        title: "ЕГЭ по математике 2025: годовой курс",
        author: "Тимур Гуев",
        price: 10,
        duration: 25,
        rating: 4.5,
        image: "https://cdn.stepik.net/media/cache/images/courses/124092/cover_jwdMHqT/770d83641e7ada123cfc741e3a4be123.png",
        users: 95,
        difficulty: "Beginner",
        categories: ["graphic-design", "arts-design"],
        date: "2024-10-10",
    },
    {
        courseAddress: "EQBbFKeOGNLAX4vjeS7XvgpKFh0_3dVpampCsnXZUYyNOPKe",
        authorAddress: "0QA8-SVqn4H2dew-CzMrfzpqg2ReIQSYCFxkzpr4ZnwcunaS",
        title: "Продвинутый SQL",
        author: "Shultais Education",
        price: 17,
        duration: 18,
        rating: 4.7,
        image: "https://cdn.stepik.net/media/cache/images/courses/55776/cover_eEyK9xX/fcf6831201233dbbfb64cbf49b0a8f8f.png",
        users: 68,
        difficulty: "Beginner",
        categories: ["finance", "personal-development"],
        date: "2024-09-22",
    },
    {
        courseAddress: "EQBbFKeOGNLAX4vjeS7XvgpKFh0_3dVpampCsnXZUYyNOPKe",
        authorAddress: "0QA8-SVqn4H2dew-CzMrfzpqg2ReIQSYCFxkzpr4ZnwcunaS",
        title: "Академия продаж. Менеджер по продажам",
        author: "Сергей Шинкарский",
        price: 40,
        duration: 60,
        rating: 5,
        image: "https://cdn.stepik.net/media/cache/images/courses/194388/cover_YEBkk5W/81ec3ca1fc87771f660d0a5e249add6f.png",
        users: 200,
        difficulty: "Beginner",
        categories: ["ai", "computer-science"],
        date: "2025-01-03",
    },
    {
        courseAddress: "EQBbFKeOGNLAX4vjeS7XvgpKFh0_3dVpampCsnXZUYyNOPKe",
        authorAddress: "0QA8-SVqn4H2dew-CzMrfzpqg2ReIQSYCFxkzpr4ZnwcunaS",
        title: "PRO Go. Алгоритмы и структуры данных",
        author: "PRO Go",
        price: 29,
        duration: 35,
        rating: 4.6,
        image: "https://cdn.stepik.net/media/cache/images/courses/201825/cover_oWEyxEM/602a0b503fbec2e6d75d2796c535b9dd.png",
        users: 88,
        difficulty: "Intermediate",
        categories: ["project-mgmt", "business"],
        date: "2024-12-18",
    },
    {
        courseAddress: "EQBbFKeOGNLAX4vjeS7XvgpKFh0_3dVpampCsnXZUYyNOPKe",
        authorAddress: "0QA8-SVqn4H2dew-CzMrfzpqg2ReIQSYCFxkzpr4ZnwcunaS",
        title: "Microservices - паттерны и практика построения микросервисов",
        author: "Антон Ларичев",
        price: 32,
        duration: 42,
        rating: 4.9,
        image: "https://cdn.stepik.net/media/cache/images/courses/117212/cover_ihY4c8s/9cf8893e80122ccd7115a2f7210bed10.jpg",
        users: 150,
        difficulty: "Expert",
        categories: ["programming", "technology"],
        date: "2025-01-20",
    },
    {
        courseAddress: "EQBbFKeOGNLAX4vjeS7XvgpKFh0_3dVpampCsnXZUYyNOPKe",
        authorAddress: "0QA8-SVqn4H2dew-CzMrfzpqg2ReIQSYCFxkzpr4ZnwcunaS",
        title: "Разработка приложений с Flutter и Dart для IOS и Android",
        author: "TechTutors Team",
        price: 20,
        duration: 20,
        rating: 4.2,
        image: "https://cdn.stepik.net/media/cache/images/courses/191099/cover_H2CjYj2/3d3baabddf76424b3ff6df5efdba9933.png",
        users: 47,
        difficulty: "Beginner",
        categories: ["history", "academic-subjects", "databases"],
        date: "2024-11-01",
    },
    {
        courseAddress: "EQBbFKeOGNLAX4vjeS7XvgpKFh0_3dVpampCsnXZUYyNOPKe",
        authorAddress: "0QA8-SVqn4H2dew-CzMrfzpqg2ReIQSYCFxkzpr4ZnwcunaS",
        title: "Командная строка Linux",
        author: "Fedor Ivanov",
        price: 22,
        duration: 30,
        rating: 4.3,
        image: "https://cdn.stepik.net/media/cache/images/courses/171984/cover_8BUN3lt/7e349274122c840e1b100465342d7bdc.png",
        users: 72,
        difficulty: "Intermediate",
        categories: ["databases", "programming"],
        date: "2024-12-05",
    },
];

export async function fetchCatalogCourses(): Promise<CatalogCourseInterface[]> {
    await new Promise((resolve) => setTimeout(resolve, 2000));
    return mockData;
}
